=== rivet-gg/modules/artifacts/module_schema.json
{"type":"object","properties":{"status":{"enum":["beta","end_of_life","maintenance","preview","stable"],"type":"string"},"name":{"description":"The human readable name of the module.","type":"string"},"description":{"description":"A short description of the module.","type":"string"},"icon":{"description":"The [Font Awesome](https://fontawesome.com/icons) icon name of the module.","type":"string"},"tags":{"description":"The tags associated with this module.","type":"array","items":{"type":"string"}},"authors":{"description":"The GitHub handle of the authors of the module.","type":"array","items":{"type":"string"}},"scripts":{"type":"object","additionalProperties":{"$ref":"#/definitions/ScriptConfig"}},"errors":{"type":"object","additionalProperties":{"$ref":"#/definitions/ErrorConfig"}},"dependencies":{"type":"object","additionalProperties":{"$ref":"#/definitions/DependencyConfig"}}},"additionalProperties":false,"required":["errors","scripts"],"definitions":{"ScriptConfig":{"type":"object","properties":{"name":{"description":"The human readable name of the script.","type":"string"},"description":{"description":"A short description of the script.","type":"string"},"public":{"description":"If the script can be called from the public HTTP interface.\n\nIf enabled, ensure that authentication & rate limits are configured for\nthis endpoints. See the `user` and `rate_limit` modules.","default":false,"type":"boolean"}},"additionalProperties":false},"ErrorConfig":{"type":"object","properties":{"name":{"description":"The human readable name of the error.","type":"string"},"description":{"description":"A short description of the error.","type":"string"}},"additionalProperties":false},"DependencyConfig":{"type":"object","additionalProperties":false}},"$schema":"http://json-schema.org/draft-07/schema#"}

=== rivet-gg/modules/modules/tokens/module.json
{
	"name": "Tokens",
	"description": "Create & verify tokens for authorization purposes.",
	"icon": "lock",
	"tags": [
		"core",
		"utility"
	],
	"authors": [
		"rivet-gg",
		"NathanFlurry"
	],
	"status": "stable",
	"scripts": {
		"create": {
			"name": "Create Token"
		},
		"fetch": {
			"name": "Fetch Token",
			"description": "Get a token by its ID."
		},
		"fetch_by_token": {
			"name": "Fetch by Token",
			"description": "Get a token by its secret token."
		},
		"revoke": {
			"name": "Revoke Token",
			"description": "Revoke a token, preventing it from being used again."
		},
		"validate": {
			"name": "Validate Token",
			"description": "Validate a token. Throws an error if the token is invalid."
		},
		"extend": {
			"name": "Extend Token",
			"description": "Extend or remove the expiration date of a token. (Only works on valid tokens.)"
		},
		"modify_meta": {
			"name": "Modify Token Metadata",
			"description": "Modify the token's associated metadata, additionally returning the old metadata. (Only works on valid tokens.)"
		}
	},
	"errors": {
		"token_not_found": {
			"name": "Token Not Found"
		},
		"token_revoked": {
			"name": "Token Revoked"
		},
		"token_expired": {
			"name": "Token Expired"
		}
	}
}
